vpn_gateway_name = "vpngw-az"
vpn_pubip_name = "vpngw-az-pubip"
vpn_type = "RouteBased"  
sku = "Standard"
sku_vpn = "VpnGw1"
type = "Vpn"
allocation_method = "Static"
ip_configuration_name = "internal"