firewall_name = "firewall-hub"
firewall_policy_name = "firewall-pol"
sku = "Standard"
sku_name = "AZFW_VNet"
sku_tier = "Premium"
private_ip_address = "10.90.34.0"
allocation_method = "Static"
pubip_name = "firewall_pubip"